name: braus # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A small application to select a browser every time you click a link anywhere
description: |
  A small application to select a browser every time you click a link anywhere. This is especially useful if you have multiple browsers or profiles, and you want to be able to open certain links in certain browsers. Very useful for web developers, but also for a lot of other people.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64, armhf]
    run-on: [amd64, armhf]

parts:
  braus:
    source: https://github.com/thecodejedi/braus.git
    source-type: git
    # See 'snapcraft plugins'
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    build-packages:
      - python3
      - python3-distutils
      - desktop-file-utils
      - appstream-util
      - gsettings-desktop-schemas-dev
      - gettext
    stage-packages:
      - python3-gi
      - python3-gi-cairo
    
apps:
  braus:
    command: usr/bin/braus
    desktop: usr/share/applications/com.properlypurple.braus.desktop